name: GCS Bucket Sync Action
description: Sync a repository with a GCS bucket

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: Bucket name
    required: true
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: '.git$'

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up